replicaCount: 1

image:
  repository: ghcr.io/manubarrionuevo/devops-academy-app
<<<<<<< HEAD
  tag: "35ee438"
=======
  tag: "latest"
>>>>>>> 4ed9393 (add devops gitops documentation)
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

containerPort: 3000

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

serviceMonitor:
  enabled: true
  interval: 15s

app:
  env: dev