name: CI

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  ci:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Run tests
        run: npm test

      - name: Audit dependencies
        run: npm audit --audit-level=high

      # -------------------------
      # SECURITY - SEMGREP
      # -------------------------
      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep
        run: semgrep scan --config auto

      # -------------------------
      # DOCKER BUILD
      # -------------------------
      - name: Build Docker image
        run: docker build -t devops-academy-app:ci .

      # -------------------------
      # SECURITY - TRIVY
      # -------------------------
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https gnupg
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb stable main" | sudo tee /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install -y trivy

      - name: Scan Docker image
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL devops-academy-app:ci